20231201_nsx_tanzu_alb

diff --git a/11_vsphere_with_tanzu/templates/tkc.sh.template b/11_vsphere_with_tanzu/templates/tkc.sh.template
--- a/11_vsphere_with_tanzu/templates/tkc.sh.template
+++ b/11_vsphere_with_tanzu/templates/tkc.sh.template
@@ -13,5 +13,26 @@ echo "${contents}" | tee -a /home/ubuntu/.profile > /dev/null
 #
 /home/ubuntu/bin/kubectl-vsphere login --insecure-skip-tls-verify --vsphere-username administrator@${sso_domain_name} --server=https://${api_server_cluster_endpoint}
 /home/ubuntu/bin/kubectl config use-context ${namespace_ref}
+/home/ubuntu/bin/kubectl apply -f ${remote_path_antrea_create}-${cluster_count}.yml
+/home/ubuntu/bin/kubectl apply -f ${remote_path_clusterbootstrap_create}-${cluster_count}.yml
 /home/ubuntu/bin/kubectl apply -f ${remote_path}-${cluster_count}.yml
 #
+# Wait for tkc cluster to be Provisioned
+#
+retry_tanzu_tkc=61
+pause_tanzu_tkc=120
+attempt_tanzu_tkc=1
+while true ; do
+  echo "attempt $attempt_tanzu_tkc to get tkc cluster config_status Provisioned"
+  tkc_status=$(/home/ubuntu/bin/kubectl get clusters ${cluster_name} -o json | jq .status.phase)
+  if [[ ${tkc_status} == "Provisioned" ]]; then
+    echo "tkc cluster ${cluster_name} is ${tkc_status} after $attempt_tanzu_tkc attempts"
+    break 2
+  fi
+  ((attempt_tanzu_tkc++))
+  if [ $attempt_tanzu_tkc -eq $retry_tanzu_tkc ]; then
+    echo "Unable to get tkc cluster Provisioned after $attempt_tanzu_tkc"
+    exit 255
+  fi
+  sleep $pause_tanzu_tkc
+done
